name: Deploy plugins to Reposilite
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew :plugins:publishAllPublicationsToReposiliteSnapshotsRepository
        env:
          REPOSILITE_USERNAME: ${{ secrets.REPOSILITE_USERNAME }}
          REPOSILITE_PASSWORD: ${{ secrets.REPOSILITE_PASSWORD }}
